# What are we going to do?
Show how accessible python is and how it could possibly be used

## Our Tool

[Pandas](https://pandas.pydata.org/docs/user_guide/10min.html) is essentially the replacement for Excel.

In [3]:
import pandas as pd

### First step opening the csv

Also known as reading the CSV file to get the data

In [5]:
df = pd.read_csv('ap_aging.csv')

Now that we have read it what is in there?

In [6]:
df.head()

,Entity,Vendor No.,Vendor Name,Vendor Type,Payment Method,Due Date,Doc Number,Accounting Id,Description,Notes,Amount
0,AZ,V000126,Algonquin Power & Utilities Corp.,PRINCIPAL,NaN,2020-08-19,NaN,09/2020 RENT,09/2020 RENT BPP TANGO INDUSTRIAL LF1 HOLDINGS,NaN,7590.84
1,HOPCO,V000030,"Sonus Networks, Inc.",CUSTOMER,NaN,2020-08-10,261313,PI115011579,228943 - 0820,NaN,35.00
2,HOPCO,V000044,"Savara, Inc.",EMPLOYEE,NaN,2020-08-19,117363,PI115011580,0720 - PACKAGING,NaN,105.75
3,HOPCO,V000044,"Savara, Inc.",EMPLOYEE,NaN,2020-09-02,117398,PI115011581,08.03.20 - PACKAGING,NaN,105.75
4,HOPCO,V000044,"Savara, Inc.",EMPLOYEE,NaN,2020-09-09,117458,PI115011582,08.10.20. - PACKAGING,NaN,105.75

What about some basic statistics so we know what we are looking at

In [7]:
df['Amount'].describe()

count      112.000000
mean      1280.353214
std       7020.879465
min     -13856.000000
25%         35.352500
50%        105.750000
75%        202.572500
max      66399.000000
Name: Amount, dtype: float64

What would we normally do with this data? Create a pivot by Entity and vendor?

How would we do this in excel?
![Intitial Excel]()

In [8]:
pd.pivot_table(df, values='Amount', index=['Entity', 'Vendor No.'], aggfunc=sum)

                     Amount
Entity Vendor No.
AZ     V000126      7590.84
HOPCO  V000007       261.20
       V000027         9.63
       V000028        40.71
       V000030        35.00
       V000031        19.38
       V000032        68.01
       V000036      2896.11
       V000037       402.18
       V000039       554.59
       V000040        60.67
       V000041      1096.79
       V000043        14.87
       V000044       317.25
       V000048       240.00
       V000051        43.08
       V000052        70.07
       V000054       472.06
       V000055        10.99
       V000064        24.80
       V000066        14.49
       V000070       498.76
       V000073        40.07
       V000079       325.44
       V000080       179.82
       V000083        48.97
HW     V000087       276.87
JGA    V000028       260.47
       V000057      1468.64
       V000090        35.47
       V000092       107.16
       V000102       383.72
       V000107       184.98
       V000115       153.00
       V000122       116.00
       V000125        84.46
SGL    V000039       160.92
       V000079       649.00
       V000143        63.13
       V000145        47.08
       V000146       450.00
       V000150        27.95
       V000155       786.32
       V000169      3983.00
       V000170       339.92
       V000172       711.42
       V000173       124.38
       V000176       350.00
       V000183       417.20
       V000186      6473.92
TCG    V000007       131.70
       V000009       561.70
       V000010     22021.80
       V000014     15000.00
       V000021    -12725.43
       V000023     66399.00
       V000024     19020.00